### ISSUE TITLE
User should be able to remove their own post.

### ISSUE THREAD

**Issue by au-chrismor** [PERRINN/client-web#4]
I hit on this today while updating the team on an issue I found, and I posted too much information.  There needs to be a way to "recall" or "delete" a message they have posted (or at least let an admin do it)

**Comment by PERRINNSoftwareTeam** [comment]
This is not a feature we want to add - the communication strategy on perrinn is the same as on the internet - if something is posted, it cannot be deleted - the aim is to avoid people deleting 'evidence' when litigating on a contract for example - I will close this
